force-app/main/default/objects/email2CaseDeduper__c/email2CaseDeduper__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>configuration for  deduping ONLY add one  record</description>
    <label>Email to Case Deduper</label>
</CustomObject>

force-app/main/default/objects/email2CaseDeduper__c/fields/queueApiNameDeleteMe__c.field-meta.xml
<CustomField>
    <fullName>queueApiNameDeleteMe__c</fullName>
    <description>The Api name of the queue to be used to send all cases that need deleting because they are duplicates</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Queue API name for deletes</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UtilEmail2CaseDuplcates.cls
public class UtilEmail2CaseDuplcates {
    
    public Static final string DuplicateCasesQName = (string)email2CaseDeduper__c.getValues('Dedupe').get('queueApiNameDeleteMe__c');   
    public Static final string DuplicateCasesQid;    
    

    //Static initialization code is a block of code preceded with the keyword static.
    //Similar to other static code, a static initialization code block is only initialized one time on the first use of the class.
	//A class can have any number of either static or instance initialization code blocks. They can appear anywhere in the code body. 
	//The code blocks are executed in the order in which they appear in the file, just as they are in Java.
	//You can use static initialization code to initialize static final variables and to declare information that is static, such as a map of values.
	// I use a single static block to call my variable initilzer methods
    static {
        DuplicateCasesQid = DuplicateCasesId();
    }   
    
    //This gets the Id value for our Email2CasePendingRouting queue from the cache
    public static string DuplicateCasesId() {
        Map<string,String> queueName2IdMap = UtilQueues.getQName2IdMap();
        return queueName2IdMap.get(DuplicateCasesQName);
    }
    
    //////////////////////////////////////////////////////////////////////////////
    public Static Void DuplicateEmailcleanup(){
        
        list<case> cases4Deletion = [Select id,ownerId from case where ownerId = :DuplicateCasesQid];
        Delete cases4Deletion;
        
    }
    
    
}