force-app/main/default/objects/DML__e/DML__e.object-meta.xml
<CustomObject>
    <label>DML</label>
    <pluralLabel>DMLs</pluralLabel>
</CustomObject>

force-app/main/default/objects/DML__e/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object Api name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PE_DML_Helper.cls
public class PE_DML_Helper {
    
    Public static void Deletes(list<DML__e> forDeleting){
        List<sobject> deletes = new list<sobject>();
        For(DML__e dml :forDeleting){
           sObject sObj = Schema.getGlobalDescribe().get(dml.Object__c).newSObject() ;
           sObj.put('id', dml.Id__c);
            System.debug(sobj);
           deletes.add(sObj);
        }
        System.debug(deletes);
        Delete deletes;
    }
        
}